# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: omansour <omansour@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/11/10 08:14:23 by omansour          #+#    #+#              #
#    Updated: 2023/11/10 09:18:45 by omansour         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS		=	main.cpp Weapon.cpp HumanA.cpp HumanB.cpp

CPPFLAGS	=	-std=c++98 -Wall -Wextra -Werror

NAME		=	violence

all	:
	c++ ${CPPFLAGS} ${SRCS} -o ${NAME}
