# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: omansour <omansour@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/11/11 05:01:45 by omansour          #+#    #+#              #
#    Updated: 2023/11/11 05:02:57 by omansour         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS		=	main.cpp Harl.cpp

CPPFLAGS	=	-std=c++98 -Wall -Wextra -Werror

NAME		=	harl

all	:
	c++ ${CPPFLAGS} ${SRCS} -o ${NAME}
