# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: omansour <omansour@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/11/10 09:25:03 by omansour          #+#    #+#              #
#    Updated: 2023/11/11 04:50:39 by omansour         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS		=	main.cpp

CPPFLAGS	=	-std=c++98 -Wall -Wextra -Werror

NAME		=	sed

all	:
	c++ ${CPPFLAGS} ${SRCS} -o ${NAME}
