# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: omansour <omansour@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/11/08 02:55:45 by omansour          #+#    #+#              #
#    Updated: 2023/11/10 03:12:52 by omansour         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS		=	main.cpp Zombie.cpp newZombie.cpp randomChump.cpp

CPPFLAGS	=	-std=c++98 -Wall -Wextra -Werror

NAME		=	BrainZ

all	:
	c++ ${CPPFLAGS} ${SRCS} -o ${NAME}
